### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by AamirHussain12** [ducnguyenedu/Data-Structures-and-Design-Patterns-for-Game-Developers#1]
I was trying to submit the week1 assignment,in which I have to submit the Target.cs and SortedList.cs files in a zip folder,i did it many times i got the following error in the image below, kindly share your zip folder for the week1 assignment that will be kind of yours.
![Screenshot (162)](https://github.com/ducnguyenedures/Coursera-Data-Structures-and-Design-Patterns-for-Game-Developers-education-source/assets/103172217/09968e25-3795-43c1-93f9-3e179d09d366)

**Comment by hideongloomist** [comment]
It was a long time ago and I no longer have it saved. This is the solution from course, which will be unlocked after you complete it. You can check out. (Because it is quite large, I will send the google drive link).
https://drive.google.com/file/d/1PzS6tdCI3_7PKRUXvxrJl0207dco8kLo/view?usp=sharing

**Comment by dusknguyen** [comment]
It was a long time ago and I no longer have saved it. This is the solution from course, which will be unlocked after you complete it. You can check out. (Because it is quite large, I will send the google drive link).
https://drive.google.com/file/d/1PzS6tdCI3_7PKRUXvxrJl0207dco8kLo/view?usp=sharing
